package com.dcl.tarea1.ui;

import javax.swing.ImageIcon;

/**
 * Gestiona el funcionamiento de la pantalla principal mediante Swing.
 * Su responsabilidad va conforme a la UI de la pantalla inicial, por lo que
 * manejará todo lo asociado a ella, incluidos sus componentes y sus eventos
 * respectivos.
 * 
 * @author David Cuadra Lara
 * @version 1.6
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private static final String APP_VERSION = "V.1.6";

    public PantallaPrincipal() {
        initComponents();

        actualizarVersion();

        /*
        Al no poder acceder al Icon Image en el JFrame, lo modificamos
        después de su iniciación.
        */
        setIconImage(new ImageIcon(
                getClass().getResource("/resources/IconHogar.png")
        ).getImage());
    }

    /**
     * Método encargado de actualizar el label de la versión.
     */
    private void actualizarVersion() {
        lblVersion.setText(APP_VERSION);
    }

    /**
     * Método encargado de crear una nueva ventana para solicitar los datos
     * del nuevo artículo.
     * 
     * @param evt 
     */
    private void altaArticuloAction(java.awt.event.ActionEvent evt) {
        
        CuestionarioArticulo ventanaAlta = new CuestionarioArticulo(this, true);
        
        ventanaAlta.setLocationRelativeTo(this);
        ventanaAlta.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        btnAnadirArticulo = new javax.swing.JButton();
        sepPrincipal = new javax.swing.JSeparator();
        mnbPrincipal = new javax.swing.JMenuBar();
        mnuGestión = new javax.swing.JMenu();
        mniAnadirArtículo = new javax.swing.JMenuItem();
        mniSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ElectroHogar - Gestión de inventario");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setName("PantallaPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 400));

        pnlPrincipal.setBackground(new java.awt.Color(140, 181, 186));
        pnlPrincipal.setForeground(new java.awt.Color(40, 123, 164));
        pnlPrincipal.setToolTipText("");
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(400, 370));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logohogar.png"))); // NOI18N
        lblLogo.setToolTipText("LogoElectroHogar.png");
        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLogo.setName(""); // NOI18N

        lblVersion.setBackground(new java.awt.Color(0, 153, 204));
        lblVersion.setFont(new java.awt.Font("Segoe UI Historic", 0, 10)); // NOI18N
        lblVersion.setForeground(new java.awt.Color(0, 0, 0));
        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblVersion.setText("Version");
        lblVersion.setToolTipText("App version");

        lblDescripcion.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescripcion.setText("Sistema de gestión de inventario especializado en el hogar");
        lblDescripcion.setToolTipText("Descripción Sistema ElectroHogar");
        lblDescripcion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnAnadirArticulo.setBackground(new java.awt.Color(102, 215, 215));
        btnAnadirArticulo.setForeground(new java.awt.Color(0, 0, 0));
        btnAnadirArticulo.setText("Añadir Articulo");
        btnAnadirArticulo.setToolTipText("Botón para añadir artículos nuevos");
        btnAnadirArticulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.lightGray));
        btnAnadirArticulo.setFocusPainted(false);
        btnAnadirArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirArticuloActionPerformed(evt);
            }
        });

        sepPrincipal.setBackground(new java.awt.Color(102, 102, 102));
        sepPrincipal.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVersion)
                .addGap(61, 61, 61))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(sepPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(btnAnadirArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 91, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion)
                .addGap(18, 18, 18)
                .addComponent(btnAnadirArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVersion)
                .addGap(18, 18, 18)
                .addComponent(sepPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLogo.getAccessibleContext().setAccessibleName("lblLogo");

        mnbPrincipal.setForeground(new java.awt.Color(102, 102, 102));
        mnbPrincipal.setToolTipText("Menu de gestión de inventario");

        mnuGestión.setText("Gestión de Inventario");

        mniAnadirArtículo.setText("Añadir Artículo");
        mniAnadirArtículo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAnadirArtículoActionPerformed(evt);
            }
        });
        mnuGestión.add(mniAnadirArtículo);

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnuGestión.add(mniSalir);

        mnbPrincipal.add(mnuGestión);

        setJMenuBar(mnbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSalirActionPerformed

    private void mniAnadirArtículoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAnadirArtículoActionPerformed
        altaArticuloAction(evt);
    }//GEN-LAST:event_mniAnadirArtículoActionPerformed

    private void btnAnadirArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirArticuloActionPerformed
        altaArticuloAction(evt);
    }//GEN-LAST:event_btnAnadirArticuloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadirArticulo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JMenuBar mnbPrincipal;
    private javax.swing.JMenuItem mniAnadirArtículo;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenu mnuGestión;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JSeparator sepPrincipal;
    // End of variables declaration//GEN-END:variables
}
